language: cpp
compiler: clang
env:
  - COMPILER=clang++-7
  - CXXFLAGS=-std=c++17
install:
  - git submodule update --init --recursive
before_script:
  - mkdir build
  - cd build
script:
  - cmake ..
  - make
