language: cpp
matrix:
  include:
    - os: linux
      compiler: clang
      env:
        - COMPILER=clang++-7
        - CXXFLAGS=-std=c++1z
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
          packages: ['g++-9', 'clang-7']

install:
  - git submodule update --init --recursive
script:
  # show OS/compiler version
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - uname -a
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..
  - make
