language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=g++-9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-9']

install:
  - git submodule update --init --recursive
script:
  # show OS/compiler version
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - uname -a
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..
  - make
