language: cpp
sudo: required
matrix:
  include:
    - os: linux
      compiler: clang
      env:
        - COMPILER=clang++-7
        - CXXFLAGS=-std=c++1z
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
          packages: ['g++-9', 'clang-7']

install:
  - git submodule update --init --recursive
script:
  # show OS/compiler version
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - uname -a
  - $CXX --version
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test
  - sudo make install
  - GOSH_FHIRworks2020_datamasker --mask --api=https://gist.githubusercontent.com/magetron/cf8e0de347e333c67f8e66c13572b111/raw/7046cca2915f6e9b68bed9c409e6e02a6cc5709e/patients.json

